spring:
  batch:
    job:
      enabled: true
      name: employeeJobCase2


datasource:
  company:
    url: jdbc:mysql://localhost:3306/company?useSSL=false&serverTimezone=Asia/Seoul&autoReconnect=true
    username: sa
    password: sa
    driverClassName: com.mysql.cj.jdbc.Driver
    maximumPoolSize: 10
    maxLifeTime: 55000
    poolName: "company-pool"
