spring:
  batch:
    job:
      name: employeeTestJob1
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#        use_sql_comments: true

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
      hibernate:
        type:
          descriptor:
            sql: TRACE
    root: INFO

datasource:
  company:
    url: jdbc:mysql://localhost:3306/company?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&autoReconnect=true
    username: sa
    password: sa
    driverClassName: com.mysql.cj.jdbc.Driver
    maximumPoolSize: 10
    maxLifeTime: 55000
    poolName: "company-pool"
